### ISSUE TITLE
Envelope and Internal load breakdown measure breaking while running the simulation

### ISSUE THREAD

**Issue by rwadhwa910** [openstudiocoalition/OpenStudioApplication#231]
Issue overview

Not able to run Envelope and Internal Load breakdown measure, It will run for the first time and then when I try to run the model again some files from the measures will get deleted as shown in the video.

The files in the measures were deleted from the folder after the simulation failed.

https://www.youtube.com/watch?v=15gJ_g1PFFA 

I have attached the link to the project.
https://drive.google.com/file/d/1EaYlJ4ydpF21mmhpAiZAI0Ct8za2mHbV/view?usp=sharing

Also when you try to add the measure after the failed simulation and run the model again it crashes, linked to "issue #177"

## Current Behavior
Simulation is getting failed because of certain files getting deleted from the measure folder. 

## Expected Behavior
Simulation should run without any error.

## Steps to Reproduce
1. Add the measure from the repo.
2. Run it and see the files in the measure before and after.

OS 1.0.1, Windows 10

**Comment by jmarrec** [comment]
Link to the project is gone.

Also, you shouldn't have the model companion folder open in the Windows Explorer while you try to run a simulation. The reason is that the companion folder is copied to a temp dir, the simulation executes, and then it tries to copy that temp folder back to the actual location on disk. If you have it open in Windows Explorer, you can't because it has a handle on the folder which makes it not writable.

If you retest with 1.2.0rc6 (or 1.2.0 if posted), and provide files again I will reopen. Thanks for opening the issue in the first place, and sorry about the delay in treating your issue.
