### ISSUE TITLE
Update OpenStudio Standards Library OSMs

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#232]
Enhancement Request
--------------
OpenStudio Application ships with a library of standards OSM files.  We want to keep these up to date with OpenStudio Standards.

## Possible Implementation
Want a script that can be run to update these

Orthogonal to: https://github.com/openstudiocoalition/OpenStudioApplication/issues/124

**Comment by macumber** [comment]
Based off of export_openstudio_libraries in openstudio-standards

https://github.com/NREL/openstudio-standards/blob/e08fcfde63ff6a4af5ce12b0aa70208024596c86/data/standards/export_OpenStudio_libraries.rb#L15

**Comment by jmarrec** [comment]
@macumber FYI last time I ran that os-standardsscript (2 years ago almost exactly), I made it parallel.

It still took 19 hours to finish, on a 8 core 16 threads machine, and about 1/4 or 1/3 of the library files didn't successfully generate.  OpenStudio hadn't done the update since then, we just had version translation-ed these files from release to release. Cf history on the 2.9.X-LTS branch: https://github.com/NREL/OpenStudio/commits/2.9.X-LTS/openstudiocore/src/openstudio_app/Resources/90_1_2004.osm


In https://github.com/openstudiocoalition/OpenStudioApplication/commit/1038789f17fd92ba83fe6f472bf2443c37c6d568 I added a github actions that will run for PRs to master (which we should do to prepare for each release), and throw if the OSMs don't match the expected OpenStudio SDK version.

**Comment by macumber** [comment]
Yeah that is a good idea to add that check on merge to master.  Are you just suggesting that we run that script and start it sooner rather than later?  I can run it

**Comment by macumber** [comment]
Ok, I see, I got myself confused on my own issue.  One approach is to simply version translate the existing files.  The second (and better) approach is to re-export the files from current standards.  

I don't think the HVAC library can be exported from the standards, is that right?  That is a hand maintained file?

**Comment by jmarrec** [comment]
There are two files:

* Check if OSM versions are ok (github actions implemented): https://github.com/openstudiocoalition/OpenStudioApplication/blob/1038789f17fd92ba83fe6f472bf2443c37c6d568/developer/ruby/CheckOSMVersions.rb#L1

* Update OSM libraries: Manual, because you need to decide **when** to do that. The IO Freeze for the SDK and all required VT needs to be correctly set up first: https://github.com/openstudiocoalition/OpenStudioApplication/blob/1038789f17fd92ba83fe6f472bf2443c37c6d568/developer/ruby/UpdateOSMVersions.rb#L1

The HVAC Library is a hand maintained file. And if you were to add new objects to it before the IO Freeze / VT is complete, you should prepare a diff file or ruby script to add the new object, instead of VT'ing the entire library, or you could end up in a broken state later.

**Comment by jmarrec** [comment]
I fixed this already: https://github.com/openstudiocoalition/OpenStudioApplication/blob/develop/.github/workflows/export_standards_data.yml
