### ISSUE TITLE
Missing fields for some measures in the measure tab

### ISSUE THREAD

**Issue by muh182** [openstudiocoalition/OpenStudioApplication#267]
Issue overview
--------------
The new version of OpenStudio (version 1.0.1) does not show extra fields for some measures (i.e., ExpertMetertoCSV: https://bcl.nrel.gov/node/83269). This is a different behavior than the older versions of OpenStudio such as version 2.8.0. 

## Current Behavior
The following image shows that in the right hand side, it is not possible to put any inputs:

<img width="935" alt="Screen Shot 2020-11-07 at 4 59 18 PM" src="https://user-images.githubusercontent.com/2249257/98453049-9c4b9f00-211a-11eb-9a32-7faf49eb6c30.png">

## Expected Behavior
From my last year notes, this is the expected behavior. The meter name can be added:
<img width="944" alt="Screen Shot 2020-11-07 at 5 01 44 PM" src="https://user-images.githubusercontent.com/2249257/98453087-f77d9180-211a-11eb-8b24-a051592fd476.png">

## Steps to Reproduce
1. Add Meter measure
2. Add ExpertMetertoCSV measure

I can share some sample models if needed. 

### Environments
Tried on both Mac and Windows

**Comment by macumber** [comment]
@muh182 for some reason ExpertMetertoCSV is not included in https://github.com/NREL/openstudio-common-measures-gem/tree/develop/lib/measures

The issue with the measure on BCL is that the arguments method is missing the model input to the arguments method.  Changing the arguments method to `def arguments(model=nil)` resolved the issue for me.

Another issue is that measures with errors result in malformed XML (multiple root elements).  This is no longer supported by the XML parser that replaced the QtXML parser.  This is possibly related to https://github.com/NREL/OpenStudio/issues/3790.  I thought there was another issue specifically for this.  The measure XML schema needs to change so that errors are reported underneath the root element.

@DavidGoldwasser should ExpertMetertoCSV be added to the common measures and re-pushed to BCL?

**Comment by muh182** [comment]
Thanks @macumber for looking into the source of this issue.

**Comment by macumber** [comment]
Closing and linking to underlying issue https://github.com/NREL/OpenStudio/issues/4147

**Comment by DavidGoldwasser** [comment]
I can check with @mdahlhausen if he wants to maintain that add add to common measures.

**Comment by mdahlhausen** [comment]
@DavidGoldwasser it's a simple update.  Yeah, we should maintain it.  I don't want to add it to gems but it should be available on BCL.
