### ISSUE TITLE
My Model list does not show cooling towers

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#269]
Issue overview
--------------
My Model list does not show cooling towers

## Current Behavior
![2020-11-11](https://user-images.githubusercontent.com/69771412/98874574-5e5abd80-242f-11eb-8940-87cc1ef90f47.png)

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):

**Comment by jmarrec** [comment]
@macumber @Ski90Moo Does it really make sense to have it show on "My Model List". The fix is easy, but usually stuff you see in "My Model List" on the loops tab is because either:

* This is a component you define somewhere else (eg a children of a ZoneHVAC object)
* This is component that can be added to 2+ loops, so that when you drag it from the library it gets added to its primary loop, but then you can drag it from the My model to add it to the secondary (or tertiary) PlantLoop/AirLoopHVAC

A cooling tower belongs on ONE loop only, so it falls it neither category.

**Comment by Ski90Moo** [comment]
It is helpful in order to duplicate the component without adding to the library.  So, for example, if I drag in a cooling tower from the library and then proceed to customize it, it becomes part of My Model.  Then, if I want to have two more just like it, I would drag two more from the My Model and drop onto the loop.  Maybe I am doing it wrong?

**Comment by jmarrec** [comment]
That's not how it works though. `clone()` method is called only when you drag from "Library", not from "My Model".

In My Model, it would be calling plantLoop.addToNode(object) instead, thus disconnecting it from any previous loops.

It would be a different feature request to allow cloning HVAC Components. (this is something I would personally do via the ruby bindings...)

**Comment by Ski90Moo** [comment]
Ok, my mistake.

**Comment by jmarrec** [comment]
No worries. The feature of being able to clone an hvac equipment is valid though. You can open a separate feature request for it. And if you can think of a good way to have that in the UI even better (right now I can't really think of one)
