### ISSUE TITLE
Crash on quit

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#29]
Reported by @DavidGoldwasser on Mac

This one may just be something developers would see. If you have both 2x and 3x app's open, then quit 3x, it crashes on quit orphaning an openstudio process. The reverse is not a problem (you can quit 2x without while 3x is open without an issue)

**Comment by DavidGoldwasser** [comment]
@tijcolem I saw this with new installer today on fresh. I've quit about 10 times and this has happened twice. If I can show how to reproduce it Ill re-open this or file a new issue.

Just to confirm since my fresh relaunch I have not launched 2.x OpenStudio or any version of PAT. When crash happens `openstudio` process is orphaned, which I then use activity monitor to mangae.

**Comment by DavidGoldwasser** [comment]
@tijcolem I thin I have a way to repeat this on mac without involving launches of 2.x app. There are three ways to quit the app. Command-Q, the pulldown menu item for "Quit OpenStudio" Under the "OpenStudioApplicaiton" menu item, and by "Exit" under the "File" menu. Note the two file menu options show Command-Q as shortcut.

Two of the three methods are fine, but if I use the "Command-Q" shortcut I get a quit unexpectedly and orphaned instance.
