### ISSUE TITLE
Save As keyboard shortcut missing

### ISSUE THREAD

**Issue by MatthewSteen** [openstudiocoalition/OpenStudioApplication#315]
Enhancement Request
--------------
The Save As shortcut is missing from 3.1.0 on Windows (haven't checked Ubuntu).

![image](https://user-images.githubusercontent.com/8397034/108390062-834c9280-71cd-11eb-9222-7e975b98d0c0.png)

## Possible Implementation
https://github.com/NREL/OpenStudio/issues/3740
https://github.com/openstudiocoalition/OpenStudioApplication/pull/45

**Comment by macumber** [comment]
It looks like that code is still there: https://github.com/openstudiocoalition/OpenStudioApplication/blob/develop/src/openstudio_lib/MainMenu.cpp#L80

The problem is that Qt doesn't define a standard shortcut for Save As on Windows (I checked a few programs, Word uses F12, Notepad++ uses Ctrl+Alt+S).  The shortcut is Ctrl+Shift+S on other platforms so maybe we should just set it to Ctrl+Shift+S for all platforms?  What do you think @MatthewSteen ?

**Comment by MatthewSteen** [comment]
> 
> The problem is that Qt doesn't define a standard shortcut for Save As on Windows (I checked a few programs, Word uses F12, Notepad++ uses Ctrl+Alt+S). The shortcut is Ctrl+Shift+S on other platforms so maybe we should just set it to Ctrl+Shift+S for all platforms? What do you think @MatthewSteen ?

Yes, `CTRL + SHIFT + S` is my recommendation based on what seems to be standard for other apps (VS Code e.g.).
