### ISSUE TITLE
Apply to selected does not work on ThermalZone Cooling or Heating Size Parameters

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#476]
Issue overview
--------------
Changes are applied but do not update until changing tabs. Likely need to add additional objects to watch on this tab

**Comment by jmarrec** [comment]
I've investigated this one a bit. On the TZ tab, the "Multiplier" works, but the stuff on the  Cooling/Heating Sizing doesn't.

The main difference is that the Multiplier is a ValueEdit concept, while the non working ones are QuantityEdit, and work through a `ProxyAdapter` (because you actually set that stuff onto the ThermalZone's SizingZone object).

Fixing it is far from trivial, as it requires delving deep into the (way too large amount of and complicated aspect of) _clever_ templates we have. I don't know how to fix it myself.

**Comment by jmarrec** [comment]
I think I got a way, but it involves a nano_emit()...
