### ISSUE TITLE
openstudio-model-articulation-gem Create Baseline Building Doesn't work

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#500]
Issue overview
--------------
I don't know if this is related to the app or if the measure is broken.  When the measure "Create Baseline Building" is executed via Apply Measure Now, it runs successfully, but the resulting model is completely empty.

## Steps to Reproduce

1.
![2022-04-20](https://user-images.githubusercontent.com/69771412/164286475-c1ab4bf6-f4a8-4246-adc0-a23cb94147fc.png)

2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):
![2022-04-20 (1)](https://user-images.githubusercontent.com/69771412/164286556-aa3fb5a5-b6c0-45f7-9628-f0f7eb5c2cf9.png)

**Comment by jmarrec** [comment]
This is probably unrelated to the OS App.

@Ski90Moo Are you applying this measure **on a valid proposed building**? You are trying to apply the "Create Baseline Building" measure, not the "Create DOE Prototype Building". That measure uses your proposed model to create a baseline:
* The geometry must be defined and the proposed HVAC system must be defined, so that the determination of the system type number for the baseline works
* Your space types must have a the Standards measure tags assigned correctly

![image](https://user-images.githubusercontent.com/5479063/174737616-8792075b-d14e-4b17-9f04-14b292747435.png)

I'm preemptively closing this issue, but happy to reopen if you provide more information to reproduce a bug on our end.

**Comment by Ski90Moo** [comment]
Hello @jmarrec , my apologies!  Yes, I was trying to create the DOE prototype building, but evidently got the two measures confused.  Thank you.

**Comment by jmarrec** [comment]
No problem @Ski90Moo . I am most grateful you report issues, and wouldn't trade a few mishaps for the actual ones you do find and describe well!
