### ISSUE TITLE
HVAC tab for VRF does not zoom

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#560]
Issue overview
--------------

Zoom buttons do not function.  Also, unable to return to the VRF main overview page.
## Current Behavior

![2022-08-30](https://user-images.githubusercontent.com/69771412/187522344-00b85f98-9910-4c64-9add-7b6edf7e2d54.png)

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 11 Pro
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):
![2022-08-30 (1)](https://user-images.githubusercontent.com/69771412/187522765-92658dec-5d9c-4a5b-9e09-c44e8268efda.png)

**Comment by macumber** [comment]
The VRF page is a bit weird because the zoom button is associated with zooming in on a particular VRF system.

Zooming in on a particular system:
![image](https://user-images.githubusercontent.com/1327850/188531235-25f115be-8772-410d-8700-a5d37aec9e4e.png)

Returning to the main overview:
![image](https://user-images.githubusercontent.com/1327850/188531149-6559454b-2fdc-4b46-b603-246be774521b.png)

I agree it is not good to show the regular zoom/unzoom buttons on that page.  Do you think it would be sufficient to just hide them when editing VRF systems?
