### ISSUE TITLE
Copying an Airloop doubles the components

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#600]
Issue overview
--------------
Using the copy button with an airloop with air-to-air heat exchanger doubles the number of heat exchangers:
![2023-04-13](https://user-images.githubusercontent.com/69771412/231789411-8e74088b-856e-4c49-8c39-8ea3f452fffa.png)

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 11 Pro
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):
![2023-04-13 (1)](https://user-images.githubusercontent.com/69771412/231789563-242dd218-a3cd-427c-8b30-da9c20df6713.png)

**Comment by Ski90Moo** [comment]
Thank you @jmarrec. I will try.  Can you give me some pointers as to where the line is drawn?

**Comment by jmarrec** [comment]
I know it's tricky without knowing the inner code of the OSApp and where it defers to OS SDK, and it's totally fine if some issues are reported to the wrong project. Ideally you should try to do the same in the OS SDK bindings and see if it crashes there. But I can try to give a couple of pointers

## Most likely OpenStudioApplication related

* Anything UI related: a button not displaying, something too big, icon missing, etc
* Anything related to geometry editor or viewing reports
* If something crashes when you switch tabs
* Dragging a component from the library to your model makes it crash
* Editing a value makes the App crash

## Potentially OS SDK related

Like I said, ideally you do the same in the SDK bindings and see.

* Clicking on x2 button makes it crash (this is usually just a call to the SDK's ModelObject::clone method)
* I'm sure I connected components correctly but I get an E+ fatal error (or crash)
* This component is not allowed in this location when trying to add a component to a loop


**When in doubt, do report to OpenStudioApplication and not OS SDK since you found the issue in the OSApp.**

**Comment by jmarrec** [comment]
Should be fixed via https://github.com/NREL/OpenStudio/pull/4872 FYI

**Comment by Ski90Moo** [comment]
Thank you @jmarrec
