### ISSUE TITLE
`sync project measures with library` does not work as before

### ISSUE THREAD

**Issue by JanghyunJK** [openstudiocoalition/OpenStudioApplication#620]
Issue overview
--------------
I think it is obvious that this is happening after switching to 1.6. I use `sync project measures with library` button (marked in the screenshot below) a lot when working on OS measures and I can't seem to update the measure with this button anymore. More specifically, I usually let the measure be placed under "OpenStudio Measures" box and click `sync project measures with library`. This worked before but not anymore. But there is a workaround by removing the measure from the box, re-add measure to the box, and click `sync project measures with library`. But it's like extra 10 seconds to work on...

![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/26775789/3e7b335f-7ed0-41a6-b4c4-ee8d0aa8bbd0)

## Current Behavior
change in the measure code does not get updated in the app

## Expected Behavior
I would want the change in the measure code be updated quickly

## Steps to Reproduce
I can't think of a way other than other person just try a measure code change and hitting the button.

## Possible Solution
unsure

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): windows
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.6.0
 
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/26775789/37069c54-6cc2-48fd-bcfd-8e134c8e1da8)

### Context
extra 10 seconds whenever making change to the measure and applying to the building model

**Comment by macumber** [comment]
Hi @JanghyunJK I'm not able to reproduce this.  I set My Measures directory to a directory with a measure in it, then dragged the measure into my model and saved the model.  I updated the measure and pressed the Sync Project Measures With Library and saved the model.  My updates to the measure were copied to the model's measures directory and the arguments were updated in the app.  Can you check a few things:

- Click the Open My Measures Directory button and make sure that is the directory you are working on your measure in
- Delete the measure from your model and re-add it from the library, check if the source is "My" instead of "BCL" when you drag it in
- Does your updated measure have any errors, does it show up with a broken icon in the library, does it run correctly in your model?

**Comment by macumber** [comment]
I did notice a new issue where the measure in my measures directory always shows as having an update because the measure in my measures has a `docs/.gitkeep` file that is listed in the measure.xml file in my measures directory but doesn't get copied or listed in the model's measures directory.

**Comment by JanghyunJK** [comment]
Hi @macumber, sorry for following up this late (had to pass the end of FY). While I was working on measure dev work until now I noticed couple more things.

- this is not like it happens right away
- it works for a while and then I get to this point where the measure does not get updated with that button
- and I tend to use `openstudio measure --update [path-to-measure]` if I was making changes to like input args for the measure
- but, I think, if I just use the above cmd everytime I make any change to the measure, then I think the button works
- so I did found a way to update measure (with one additional step)
- unsure if this is what is expected tho!
