### ISSUE TITLE
Defaults for Zone and System Sizing

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#693]
Thank you @macumber. 

I have encountered this issue before, but I think I confused the diagnosis when I posted this issue.  It appears that the default when creating a new OS model is that Do Zone Sizing Calculation and Do System Sizing Calculation is toggled off.  Why is that?  Without input from the users, I think by default these should be toggled on.  For example, when I import spaces, create thermal zones and thermostats, and add an autosized Packaged Rooftop Air Conditioner and assign zones to the diffusers, these two remain toggled off.  It then gives this error and the user has to diagnose the problem.

_Originally posted by @Ski90Moo in https://github.com/openstudiocoalition/OpenStudioApplication/issues/691#issuecomment-2006477288_

**Comment by jmarrec** [comment]
By default your model is empty. But we (the osapp) do initialize some of the singleton objects, one of which is the Simulation Control. Create a new model in the os app, save it as empty.osm, and looks inside you'll find this

```
OS:SimulationControl,
  {23c5d2a2-2d45-4ccf-93dc-fc30c0a4429d}; !- Handle
```

So this is the same as doing in ruby

```ruby
require 'openstudio'
include OpenStudio::Model
m = Model.new
sc = m.getSimulationControl
puts sc
```

```
OS:SimulationControl,
  {4bcbb5aa-0e97-4416-8e8f-5ca2ddd390ac}; !- Handle
```


This is all defaulted.

```
[5] energyplus(main)> sc.doZoneSizingCalculation
=> false
[6] energyplus(main)> sc.isDoZoneSizingCalculationDefaulted
=> true
```

So we report false, because that's what the getter gives us. And we do not want to hard-assign it to yes, because of the OS SDK EnergyPlus FT which tries to be smart about it, a behavior we want to retain.

https://github.com/NREL/OpenStudio/blob/9165cdc1f5e42d8ea33c2fe3a428a7b48025d76b/src/energyplus/ForwardTranslator/ForwardTranslateSimulationControl.cpp#L41-L47

I think that logic should be in the modelobject, not the FT though.

**Comment by jmarrec** [comment]
Not an OSApp issue to me, https://github.com/NREL/OpenStudio/issues/1472 . @Ski90Moo You ok if I close this one given the explanations above?

**Comment by jmarrec** [comment]
I think this PR should address this https://github.com/NREL/OpenStudio/pull/5118

**Comment by Ski90Moo** [comment]
Thank you @jmarrec
