### ISSUE TITLE
Windows: Machine restart required to completely uninstall app

### ISSUE THREAD

**Issue by eomere** [openstudiocoalition/OpenStudioApplication#71]
Issue overview
--------------

The windows version of the app does not completely uninstall when prompted.
## Current Behavior

The directory containing all originally downloaded information does not get deleted. This is because it holds a bin file that won't delete. Upon restarting the computer, both the directory and bin file were deleted.
## Expected Behavior

When uninstalled, all items associated with the app should be deleted.
## Steps to Reproduce

Install the app, then uninstall it.

**Comment by macumber** [comment]
It's possible that orphan CLI processes were holding this folder locked.  When this happens next can you use [unlocker](http://www.emptyloop.com/unlocker/) to see which process it is?  If it is `openstudio` then there is a good chance that will be fixed in https://github.com/openstudiocoalition/OpenStudioApplication/issues/369

**Comment by jmarrec** [comment]
Assuming it's fixed by #369, and if not need more info to reproduce. Happy to reopen if bug is confirmed with 1.2.0 (or 1.2.0-rc6) and  more info is provided
